services:
  - type: web
    name: movieflix-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false